version: '3.8'

services:
  django:
    build:
      context: .
    container_name: django
      #command: sh -c './entrypoint.sh'
    ports:
      - "8000:8000"
    environment:
      #DJANGO_SETTINGS_MODULE: django_project.settings
      DB_HOST: db
      DB_NAME: django_db
      DB_USER: django_user
      DB_PASSWORD: django_password
        #depends_on:
        #  - db

        #  db:
        #    image: mysql:8.0
        #    container_name: mysql_db
        #    environment:
        #      MYSQL_ROOT_PASSWORD: root_password
        #      MYSQL_DATABASE: django_db
        #      MYSQL_USER: django_user
        #      MYSQL_PASSWORD: django_password
        #    ports:
        #      - "3306:3306"
        #    volumes:
        #      - mysql_data:/var/lib/mysql
        #
        #volumes:
        #  mysql_data:

