# Generated by Django 5.1.3 on 2024-12-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('accepted', 'Rejected'), ('rejected', 'Accepted')], default='pending', max_length=20),
        ),
    ]
